Repository kymckay/f28cd-project, pull requests merged in 2021-03, with the labels that each got.

#28 Refactor dropdown code
  public/css/dropdown.css
  public/index.html
  public/src/dropdown.js
  public/src/main.js
Labels: dev/frontend

#31 Add data extraction and loading script
  .eslintrc.json
  CONTRIBUTING.md
  data/README.md
  data/build_db.js
  data/load_candidates.js
  data/load_elections.js
  package-lock.json
  package.json
  server/data/README.md
  server/data/build_db.js
Labels: dev/data

#34 Initial map implementation
  .gitignore
  CONTRIBUTING.md
  data/mapbox_inject.js
  data/mapbox_remove.js
  data/secrets_template.json
  package.json
  public/css/main.css
  public/index.html
  public/src/main.js
Labels: dev/frontend

#36 Initial front end implementation
  .gitignore
  CONTRIBUTING.md
  data/mapbox_inject.js
  data/mapbox_remove.js
  data/secrets_template.json
  package.json
  public/assets/cand1.jpg
  public/assets/logo.png
  public/css/dropdown.css
  public/css/info.css
  public/css/legend.css
  public/css/main.css
  public/css/search.css
  public/css/table.css
  public/index.html
  public/src/candSect.js
  public/src/dropdown.js
  public/src/graph.js
  public/src/main.js
  public/src/search.js
  public/src/sort.js
  public/src/test.csv
Labels: dev/frontend

#49 Request year's data on dropdown change
  public/src/dropdown.js
  public/src/main.js
  server/server.js
Labels: dev/backend, dev/frontend

#48 Custom dropdown formatting
  public/css/dropdown.css
  public/css/legend.css
  public/css/main.css
  public/index.html
Labels: dev/frontend

#52 Add AJAX request to get years on page load
  public/css/dropdown.css
  public/index.html
  public/src/dropdown.js
  public/src/dropdowns.js
  public/src/list.js
  public/src/main.js
  public/src/map.js
  public/src/requests.js
  public/src/search.js
  public/src/sort.js
  server/server.js
Labels: dev/backend, dev/frontend

#61 Get year's data from the server
  data/build_db.js
  data/load_candidates.js
  public/css/legend.css
  public/css/table.css
  public/index.html
  public/src/candidate.js
  public/src/dropdowns.js
  public/src/graph.js
  public/src/list.js
  public/src/main.js
  public/src/requests.js
  server/database.js
  server/server.js
Labels: dev/backend, dev/data, dev/frontend

#68 Add prediction data generation and cumulative party data
  data/build_db.js
  data/load_candidates.js
  server/database.js
  server/server.js
Labels: dev/backend, dev/data

#70 Improve party legend
  public/src/list.js
Labels: dev/frontend

#72 Handle failed MongoDB connection gracefully
  server/database.js
Labels: dev/backend

#75 Update graph with real data
  public/src/dropdowns.js
  public/src/graph.js
  public/src/requests.js
  public/src/test.csv
Labels: dev/frontend

#80 Safeguard against NoSQL queries with non-strings
  server/database.js
Labels: dev/backend

#78 Style the graph using party colours
  data/load_candidates.js
  package-lock.json
  public/css/legend.css
  public/index.html
  public/src/graph.js
  public/src/list.js
  server/database.js
Labels: dev/data, dev/frontend

#82 Populate candidate section with real data
  data/build_db.js
  data/load_candidates.js
  public/assets/cand1.jpg
  public/css/info.css
  public/css/legend.css
  public/css/main.css
  public/index.html
  public/src/candidate.js
  public/src/list.js
  public/src/requests.js
  server/database.js
Labels: dev/data, dev/frontend

#90 Introduce data cache to front end
  public/src/candidate.js
  public/src/data.js
  public/src/dropdowns.js
  public/src/graph.js
  public/src/list.js
  public/src/main.js
  public/src/requests.js
Labels: dev/frontend

#92 Show party seats on graph by default
  data/build_db.js
  data/load_candidates.js
  public/src/data.js
  public/src/graph.js
  server/database.js
Labels: dev/data, dev/frontend

#94 Implement map colouring
  public/src/map.js
  public/src/requests.js
Labels: dev/frontend

#71 Fix numeric sorting of votes column
  public/src/list.js
Labels: dev/frontend

#97 Table rows clickable
  public/css/table.css
  public/src/list.js
Labels: dev/frontend

#104 Update candidate section when clicking list
  public/src/list.js
  public/src/map.js
Labels: dev/frontend

#113 Sort parties and candidates by default
  data/build_db.js
  public/src/candidate.js
  public/src/graph.js
  public/src/map.js
Labels: dev/data

#112 Add number of wins and runs to data
  data/build_db.js
  public/src/candidate.js
  server/database.js
Labels: dev/data, dev/frontend

#115 Fix party graph for constituencies with 7+ parties
  public/src/graph.js
Labels: dev/frontend

#116 Fix graph title on year change
  public/index.html
  public/src/graph.js
  public/src/map.js
Labels: dev/frontend

#117 Preserve table sorting when changing year
  public/src/list.js
Labels: dev/frontend

#119 Remove duplicate results from constituency search
  public/src/map.js
Labels: dev/frontend
